version: '3.8'
services:
  db:
    image: postgres:14-alpine
    restart: "unless-stopped"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      VOLUMES_DIR: ${VOLUMES_DIR}
    volumes:
        - "./volumes/pg-data:/var/lib/postgresql/data"
    ports:
        - "${DB_PORT}:5432"
